"""Separate notes from annotation

Revision ID: 150a07f5062d
Revises: ea4373b46ec4
Create Date: 2020-11-05 22:08:02.174679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150a07f5062d'
down_revision = 'ea4373b46ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('parser', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('annotations', sa.Column('note_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fkey_note_id', 'annotations', 'notes', ['note_id'], ['id'])
    op.add_column('documents', sa.Column('note_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fkey_note_id', 'documents', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
    # My code below

    # Temporary column
    op.add_column('notes', sa.Column('_ann_id', sa.Integer(), nullable=False))
    # Create notes from existing notes
    x = op.execute("""
        INSERT INTO notes (user_id, body, parser, _ann_id)
        SELECT user_id, blob, parser, id FROM annotations
    """)
    # Link foreign key
    x = op.execute("""
        UPDATE annotations
        SET note_id=n.id
        FROM annotations a
        INNER JOIN notes n
        ON n._ann_id=a.id
        WHERE annotations.id=n._ann_id
    """)
    # Delete temporary column
    op.drop_column('notes','_ann_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_note_id', 'documents', type_='foreignkey')
    op.drop_column('documents', 'note_id')
    op.drop_constraint('fkey_note_id', 'annotations', type_='foreignkey')
    op.drop_column('annotations', 'note_id')
    op.drop_table('notes')
    # ### end Alembic commands ###
