"""Note threads

Revision ID: a0f97e4f4ce2
Revises: 0b16e941493d
Create Date: 2022-01-30 23:30:22.755129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f97e4f4ce2'
down_revision = '0b16e941493d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_answer', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('is_question', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('parent_note_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fkey_parent_note_id', 'notes', 'notes', ['parent_note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_parent_note_id', 'notes', type_='foreignkey')
    op.drop_column('notes', 'parent_note_id')
    op.drop_column('notes', 'is_question')
    op.drop_column('notes', 'is_answer')
    # ### end Alembic commands ###
