"""Note tags

Revision ID: e77ac52b58bf
Revises: 150a07f5062d
Create Date: 2020-11-23 09:43:39.235494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77ac52b58bf'
down_revision = '150a07f5062d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_tags',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='fkey_note_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fkey_tag_id')
    )
    op.drop_column('annotations', 'parser')
    op.drop_column('annotations', 'blob')
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'last_modified_at')
    op.drop_column('notes', 'last_accessed_at')
    op.drop_column('notes', 'created_at')
    op.add_column('annotations', sa.Column('blob', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('annotations', sa.Column('parser', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('notes_tags')
    # ### end Alembic commands ###
