"""Keep track of latest creation/modification/access times

Revision ID: ea4373b46ec4
Revises: dc241a7b17e6
Create Date: 2020-11-01 21:46:35.051235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4373b46ec4'
down_revision = 'dc241a7b17e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'read')
    op.drop_column('documents', 'last_modified_at')
    op.drop_column('documents', 'last_accessed_at')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###
